publish_to: none
name: weather1
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  http: ^0.13.4
  provider: ^6.0.3
  recase: ^4.0.0




  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/loading.gif
    - .env
dev_dependencies:
  lints: ^2.0.1

